import { Michroma } from 'next/font/google'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from './componands/navbar/navbar'
import Footer from './componands/footer/footer';
import ReduxProvider from './ReduxProvider'

const michroma = Michroma({
  subsets: ['latin'], 
  weight: '400',      
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "B & W",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <Navbar className={michroma.className} /> 
            {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
